############
### BASE ###
############

FROM oven/bun:1.2.2 as base

#################
### INSTALLER ###
#################

FROM base as installer

WORKDIR /usr/src/app

COPY . .

RUN bun install
RUN bunx playwright install-deps chromium

##############
### RUNNER ###
##############

FROM base as runner

WORKDIR /usr/src/app

COPY --from=installer /usr/src/app .

CMD bun run migrate && bun run start

